### ISSUE TITLE
/addplaylist bug with invalid playlistID

### ISSUE THREAD

**Issue by twamp22** [heylistenio/heylisten#1]
I noticed when using the /addplaylist command with an ID that is not supported, causes the chat to output the login/MOTD. After this point if the user then adds a video to the queue manually, it will play that video instantly and will delete any existing playlist that is queued.

You can easily reproduce this:
-Queue two or more videos
-Type: /addplaylist XXXXXXXXXXXXXXXXXXXXXXXXXXXX 1
-Chat should show the MOTD
-Queue a normal video into the playlist
-The newest video should have wiped the playlist and started the single video

  Great service, let me know if you need anymore info or if you have trouble reproducing it!

**Comment by frecel** [comment]
This is pretty bad, that behaviour suggests that adding a playlist crashes the entire server. Thank you for reporting it.

It probably doesn't happen in the dev branch since this portion of the code has been through some significant changes. Since the dev is not quite ready to be merged with master at this point I will do my best to add a hotfix to master today.

**Comment by twamp22** [comment]
Yea man, no problem!

**Comment by frecel** [comment]
This is now fixed in master
